// This code was generated by `SqlHydra.Sqlite` -- v3.4.0-beta.1.
namespace Sqlite.AdventureWorksNet8

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 4, 0)
    let ns = "Sqlite.AdventureWorksNet8"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Address =
        { AddressID: int64
          AddressLine1: string
          AddressLine2: Option<string>
          City: string
          StateProvince: string
          CountryRegion: string
          PostalCode: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let Address = table<Address>

    [<CLIMutable>]
    type BuildVersion =
        { SystemInformationID: int64
          ``Database Version``: string
          VersionDate: System.DateTime
          ModifiedDate: System.DateTime }

    let BuildVersion = table<BuildVersion>

    [<CLIMutable>]
    type Customer =
        { CustomerID: int64
          NameStyle: int64
          Title: Option<string>
          FirstName: string
          MiddleName: Option<string>
          LastName: string
          Suffix: Option<string>
          CompanyName: Option<string>
          SalesPerson: Option<string>
          EmailAddress: Option<string>
          Phone: Option<string>
          PasswordHash: string
          PasswordSalt: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let Customer = table<Customer>

    [<CLIMutable>]
    type CustomerAddress =
        { CustomerID: int64
          AddressID: int64
          AddressType: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let CustomerAddress = table<CustomerAddress>

    [<CLIMutable>]
    type ErrorLog =
        { ErrorLogID: int64
          ErrorTime: System.DateTime
          UserName: string
          ErrorNumber: int64
          ErrorSeverity: Option<int64>
          ErrorState: Option<int64>
          ErrorProcedure: Option<string>
          ErrorLine: Option<int64>
          ErrorMessage: string }

    let ErrorLog = table<ErrorLog>

    [<CLIMutable>]
    type Product =
        { ProductID: int64
          Name: string
          ProductNumber: string
          Color: Option<string>
          StandardCost: int64
          ListPrice: int64
          Size: Option<string>
          Weight: Option<int64>
          ProductCategoryID: Option<int64>
          ProductModelID: Option<int64>
          SellStartDate: System.DateTime
          SellEndDate: Option<System.DateTime>
          DiscontinuedDate: Option<System.DateTime>
          ThumbNailPhoto: Option<byte[]>
          ThumbnailPhotoFileName: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    let Product = table<Product>

    [<CLIMutable>]
    type ProductCategory =
        { ProductCategoryID: int64
          ParentProductCategoryID: Option<int64>
          Name: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let ProductCategory = table<ProductCategory>

    [<CLIMutable>]
    type ProductDescription =
        { ProductDescriptionID: int64
          Description: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let ProductDescription = table<ProductDescription>

    [<CLIMutable>]
    type ProductModel =
        { ProductModelID: int64
          Name: string
          CatalogDescription: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    let ProductModel = table<ProductModel>

    [<CLIMutable>]
    type ProductModelProductDescription =
        { ProductModelID: int64
          ProductDescriptionID: int64
          Culture: string
          rowguid: string
          ModifiedDate: System.DateTime }

    let ProductModelProductDescription = table<ProductModelProductDescription>

    [<CLIMutable>]
    type SalesOrderDetail =
        { SalesOrderID: int64
          SalesOrderDetailID: int64
          OrderQty: int64
          ProductID: int64
          UnitPrice: int64
          UnitPriceDiscount: int64
          LineTotal: int64
          rowguid: string
          ModifiedDate: System.DateTime }

    let SalesOrderDetail = table<SalesOrderDetail>

    [<CLIMutable>]
    type SalesOrderHeader =
        { SalesOrderID: int64
          RevisionNumber: int64
          OrderDate: System.DateTime
          DueDate: System.DateTime
          ShipDate: Option<System.DateTime>
          Status: int64
          OnlineOrderFlag: int64
          SalesOrderNumber: string
          PurchaseOrderNumber: Option<int64>
          AccountNumber: Option<string>
          CustomerID: int64
          ShipToAddressID: Option<int>
          BillToAddressID: Option<int>
          ShipMethod: string
          CreditCardApprovalCode: Option<string>
          SubTotal: int64
          TaxAmt: int64
          Freight: int64
          TotalDue: int64
          Comment: Option<string>
          rowguid: string
          ModifiedDate: System.DateTime }

    let SalesOrderHeader = table<SalesOrderHeader>


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let compiler = SqlKata.Compilers.SqliteCompiler()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
