FROM postgres:15

# Environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=Adventureworks

# We can ADD init scripts here later
# COPY init.sql /docker-entrypoint-initdb.d/
