FROM mcr.microsoft.com/mssql/server:2022-latest

# Environment variables for default setup
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Password#123

# We can ADD init scripts here later
# COPY init.sql /docker-entrypoint-initdb.d/
