FROM gvenzl/oracle-xe:21-slim-faststart

# Environment variables
ENV ORACLE_PASSWORD=Oracle1
ENV APP_USER=OT
ENV APP_USER_PASSWORD=Oracle1

# We can ADD init scripts here later
# COPY init.sql /container-entrypoint-initdb.d/
