module SqlHydra.SchemaTemplate

open Domain

let backticks = Fantomas.FCS.Syntax.PrettyNaming.NormalizeIdentifierBackticks
let newLine = "\n"

let versionModule (cfg: Config) (v: Version.InformationalVersion) = $"""
module Version =
    let cli = System.Version({v.Version.Major}, {v.Version.Minor}, {v.Version.Build})
    let ns = "%s{cfg.Namespace}"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns
"""

let mkEnum db schema enum = stringBuffer {
    let enumType =
        db.Enums
        |> List.find (fun e -> e.Schema = schema && e.Name = enum)

    let labels =
        enumType.Labels
        |> List.sortBy _.SortOrder

    $"type {backticks enumType.Name} ="
    indent {
        for label in labels do
            $"| {backticks label.Name} = {label.SortOrder}"
    }
}

let mkTable cfg db (table: Table) schema = stringBuffer {
    let tableType =
        db.Tables
        |> List.find (fun t -> t.Schema = schema && t.Name = table.Name)

    if cfg.IsCLIMutable then "[<CLIMutable>]"

    $"type {backticks table.Name} ="
    indent {
        "{"
        indent {
            for col in tableType.Columns do
                let baseType =
                    // Handles array types: "byte[]", "string[]", "int[]", "int []", "int array"
                    if col.TypeMapping.ClrType.EndsWith "[]" || col.TypeMapping.ClrType.EndsWith "array" then
                        let baseTypeNm = col.TypeMapping.ClrType.Split([| "[]"; " []"; " array" |], System.StringSplitOptions.RemoveEmptyEntries) |> Array.head
                        $"{baseTypeNm} []"
                    else
                        col.TypeMapping.ClrType

                let columnPropertyType =
                    if col.IsNullable then
                        match cfg.NullablePropertyType with
                        | NullablePropertyType.Option ->
                            $"Option<{baseType}>"
                        | NullablePropertyType.Nullable ->
                            if col.TypeMapping.IsValueType()
                            then $"System.Nullable<{baseType}>"
                            else baseType
                    else
                        baseType

                let providerDbTypeAttribute =
                    match col.TypeMapping.ProviderDbType with
                    | Some providerDbType when cfg.ProviderDbTypeAttributes ->
                        Some $"[<ProviderDbType(\"{providerDbType}\")>]"
                    | _ ->
                        None

                if providerDbTypeAttribute.IsSome then providerDbTypeAttribute.Value
                $"""{if cfg.IsMutableProperties then "mutable " else ""}{backticks col.Name}: {columnPropertyType}"""
        }
        "}"
    }
}

let mkCompiler (providerType: ProviderType) =
    match providerType with
    | ProviderType.SqlServer -> "SqlKata.Compilers.SqlServerCompiler()"
    | ProviderType.Npgsql -> "SqlKata.Compilers.PostgresCompiler()"
    | ProviderType.MySql -> "SqlKata.Compilers.MySqlCompiler()"
    | ProviderType.Sqlite -> "SqlKata.Compilers.SqliteCompiler()"
    | ProviderType.Oracle -> "SqlKata.Compilers.OracleCompiler()"

let mkConnectionType (providerType: ProviderType) =
    match providerType with
    | ProviderType.SqlServer -> "Microsoft.Data.SqlClient.SqlConnection"
    | ProviderType.Npgsql -> "Npgsql.NpgsqlConnection"
    | ProviderType.MySql -> "MySql.Data.MySqlClient.MySqlConnection"
    | ProviderType.Sqlite -> "Microsoft.Data.Sqlite.SqliteConnection"
    | ProviderType.Oracle -> "Oracle.ManagedDataAccess.Client.OracleConnection"

let generate (cfg: Config) (provider: Provider) (db: Schema) (version: Version.InformationalVersion) = stringBuffer {
    let filteredTables =
        db.Tables
        |> List.sortBy (fun tbl -> tbl.Schema, tbl.Name)

    let schemas =
        let enumSchemas = db.Enums |> List.map (fun e -> e.Schema)
        let tableSchemas = filteredTables |> List.map (fun t -> t.Schema)
        enumSchemas @ tableSchemas |> List.distinct

    $$"""
// This code was generated by `{{provider.Name}}` -- v%%s{{version.InformationalVersion}}.
namespace {{cfg.Namespace}}
    """

    "open SqlHydra"
    "open SqlHydra.Query"

    versionModule cfg version

    for schema in schemas do
        $"module {backticks schema} ="

        let enums =
            db.Enums
            |> List.filter (fun e -> e.Schema = schema)
            |> List.map _.Name

        indent {
            for enum in enums do
                mkEnum db schema enum
                newLine
        }

        let tables =
            filteredTables
            |> List.filter (fun t -> t.Schema = schema)

        indent {
            for table in tables do
                mkTable cfg db table schema
                newLine

                if cfg.TableDeclarations then
                    $"let {backticks table.Name} = table<{backticks table.Name}>"
                    newLine
        }

    if cfg.Readers.IsSome then
        $"""
[<System.Obsolete("The HydraReader module is no longer needed and will be removed in v4.0.")>]
type HydraReader = 
    static member Read(reader: Microsoft.Data.SqlClient.SqlDataReader) : (unit -> 'T) =
        Hydration.buildRowReader<'T> Domain.ProviderType.{provider.Type} reader
        """

    // If the user configures ProviderDbTypeAttributes, we know they are using SqlHydra.Query.
    if cfg.ProviderDbTypeAttributes then
        let compiler = mkCompiler provider.Type
        let connectionType = mkConnectionType provider.Type

        $"""
[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders = ()
        """

        if provider.Type = ProviderType.Npgsql then
            $"""
type QueryContextFactory =
    {{
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
    }}
    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()
    static member Create(connectionString: string, ?sqlLogger) =
        QueryContextFactory.Create(Npgsql.NpgsqlDataSource.Create(connectionString), ?sqlLogger = sqlLogger)
    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        let compiler = {compiler}

        let createConn () : System.Data.Common.DbConnection =
            dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {{
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }}

        {{
            OpenContext = openContext
            OpenContextAsync = openContextAsync
        }}
    """
        else
            $"""
type QueryContextFactory =
    {{
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
    }}
    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()
    static member Create(connectionString: string, ?sqlLogger) =
        let compiler = {compiler}

        let createConn () : System.Data.Common.DbConnection =
            new {connectionType}(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {{
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }}

        {{
            OpenContext = openContext
            OpenContextAsync = openContextAsync
        }}
    """

}
